# -*- coding: utf-8 -*-
"""ODOO_API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yr98AfjMfiSML_TfruJzkjtN3NNfLa3Z

**CONF INIT**
"""
## EXTRACT THE VARIABLES FROM .ENV FILE

import xmlrpc.client
import base64
import unicodedata

ODOO_URL = 
ODOO_DB = 
ODOO_USERNAME = 
ODOO_PASS = 

common = xmlrpc.client.ServerProxy(f"{ODOO_URL}/xmlrpc/2/common")
uid = common.authenticate(ODOO_DB, ODOO_USERNAME, ODOO_PASS, {})

models = xmlrpc.client.ServerProxy(f"{ODOO_URL}/xmlrpc/2/object")

fields = models.execute_kw(
    ODOO_DB, uid, ODOO_PASS,
    'maintenance.equipment', 'fields_get',
    [],
    {'attributes': ['string', 'type']}
)

for f in fields:
    print(f, fields[f])

"""**OBTENER IDS**"""

categories = models.execute_kw(
    ODOO_DB, uid, ODOO_PASS,
    'maintenance.equipment.category', 'search_read',
    [[]],
    {'fields': ['id','name']}
)

print(categories)

"""**ID EMPLEADOS**"""

users = models.execute_kw(
    ODOO_DB, uid, ODOO_PASS,
    'res.users', 'search_read',
    [[]],
    {'fields': ['id','name','login']}
)
print(users)

"""**BUSCAR POR CORREO ASOCIADO**"""

tech = models.execute_kw(ODOO_DB, uid, ODOO_PASS, 'res.users', 'search_read',
    [[['login','=','sistemas@copower.com.co']]], {'fields':['id','name'], 'limit':1})
print(tech)

"""**TEAMS ID**"""

teams = models.execute_kw(
    ODOO_DB, uid, ODOO_PASS,
    'maintenance.team', 'search_read',
    [[]],
    {'fields': ['id','name']}
)

print(teams)

"""**PROVEEDORES ID Y REF**"""

partners = models.execute_kw(
    ODOO_DB, uid, ODOO_PASS,
    'res.partner', 'search_read',
    [[]],
    {'fields': ['id','name']}
)

print(partners)

# buscar una string en name que contenga la palabra "Lenovo" de forma case-insensitive
search_term = 'lenovo'.lower()
lenovo_partners = [p for p in partners if search_term in p['name'].lower()]
print("Partners containing 'Lenovo' (case-insensitive):")
for partner in lenovo_partners:
    print(partner)

partners = models.execute_kw(
    db, uid, password,
    'res.partner', 'search_read',
    [[['supplier_rank', '>', 0]]],
    {'fields': ['id', 'name', 'email', 'phone', 'supplier_rank', 'is_company']}
)
print(partners)

# cargar imagen
with open("compresor_test.jpg", "rb") as f:
    image_base64 = base64.b64encode(f.read()).decode()

equipment_data = {
    'name': 'Compresor Atlas GA555',
    'serial_no': 'ATL-22334545',
    'model': 'GA55',
    'location': 'SISTEMAS',
    'cost': 25000000,
    'rental_cost': 1500000,
    'note': '<p>Compresor principal de la línea</p>',
    'assign_date': '2026-03-16',
    'warranty_date': '2028-03-16',
    'period': 90,
    'maintenance_duration': 2.5,
    'image_1920': image_base64,
    'partner_id': 57796,

    # relaciones (IDs)
    'category_id': 25,
    'technician_user_id': 452,
    'maintenance_team_id': 42,
}

equipment_id = models.execute_kw(
    ODOO_DB, uid, ODOO_PASS,
    'maintenance.equipment',
    'create',
    [equipment_data]
)

print("Machine created:", equipment_id)

"""**VALIDATION**"""

def normalize(s):
    if not s: return ''
    s = s.strip().lower()
    s = unicodedata.normalize('NFKD', s)
    s = ''.join(c for c in s if not unicodedata.combining(c))
    return s

# preparar caches
users_list = models.execute_kw(db, uid, password, 'res.users', 'search_read', [[['active','=',True]]], {'fields':['id','name','login']})
user_by_login = {u['login']: u['id'] for u in users_list if u.get('login')}
user_by_name = {normalize(u['name']): u['id'] for u in users_list if u.get('name')}

def resolve_user_id(possible_name_or_email):
    if not possible_name_or_email:
        return None
    # intentar como email/login
    if possible_name_or_email in user_by_login:
        return user_by_login[possible_name_or_email]
    # buscar por nombre normalizado
    key = normalize(possible_name_or_email)
    return user_by_name.get(key)